# Lab 01: Getting Started

In this lab, we will walk through configuring Google Colab so that you can download the starter code for each lab, run and edit code, and then save and submit it.

Colab is a cloud-based solution that allows you to run Python and Jupyter notebooks from your browser, without having to configure anything on your personal computer.

Before continuing with this notebook, please first complete this brief tutorial: [Overview of Colab](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)

<hr>

## Command-line

Welcome back!

What Colab does is create a [virtual machine](https://en.wikipedia.org/wiki/Virtual_machine), which is like a fresh install of an operating system made just for you.

This means that in addition to running Python code in this notebook, you can also interact with the command-line as if you were using a terminal to navigate a computer. If you have never used the command-line before, it is worth reading through [this tutorial](https://computers.tutsplus.com/tutorials/navigating-the-terminal-a-gentle-introduction--mac-3855).

Notebooks also allow you to run shell commands by preceding the command with a `!`.

For example, the command below will list the current working directory where this notebook is running.

In [1]:
!pwd

/content

This tells us that we are running Ubuntu, a Linux distribution, and also says what version we're running.

To list the contents of a folder, you can use the `ls` command. This will list the contents of the current working directory:

In [2]:
!ls

sample_data

We can see the contents of the `sample_data` directory like this:

In [3]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md

If expand the left sidebar in Colab, you should see a folder icon. This will show the typical file navigation menu, and you should see the `sample_data` folder there as well.

And the following command will list information about the operating system that this notebook is running on. Note that the `cat` command prints the contents of a file. So, this is printing the contents of all files in the `/etc/` folder that end in the word `release,` which is where Linux distributions store OS information.

In [4]:
!cat /etc/*release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

## Cloning the course repository

For many labs and demos, you will need to access data that is stored in the class GitHub repository, which is here:

https://github.com/nmattei/cmps3160/

If you have never used GitHub before, git is one of the most widely used version control management systems today, and invaluable when working in a team. GitHub is a web-based hosting service built around git that supports hosting git repositories, user management, etc. There are other similar services, e.g., BitBucket and GitLab.

Our use of git/github for the class will be minimal; however, we encourage you to use it for collaboration for your class project, or for other classes, or for anything because it's great. To learn more about GitHub, see [this tutorial](https://docs.github.com/en/get-started/quickstart/hello-world). Note -- you don't need to do that tutorial to complete this notebook.

The main thing we want to do is clone the course files into this Colab virtual machine. To do so, we will issue a `git clone` command. This will copy all the files from the course Github to our virtual machine:

In [5]:
!git clone https://github.com/nmattei/cmps3160.git

Cloning into 'cmps3160'...
remote: Enumerating objects: 2481, done.
remote: Counting objects: 100% (469/469), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 2481 (delta 404), reused 370 (delta 340), pack-reused 2012 (from 1)
Receiving objects: 100% (2481/2481), 55.21 MiB | 33.25 MiB/s, done.
Resolving deltas: 100% (1530/1530), done.

We should now see a folder called `cmps3160`, which contains a copy of the GitHub repository:

In [6]:
!ls

cmps3160  sample_data

In [7]:
!ls cmps3160

404.html      _demos		  img	     _layouts	   schedule.md
CHANGELOG.md  docker-compose.yml  _includes  LICENSE	   syllabus.md
_config.yml   Dockerfile	  index.md   _projects	   tags.html
css	      Gemfile		  js	     README.md
_data	      Gemfile.lock	  _labs      resources.md

## Changing Directories

To change the current working directory, we will use the `cd` command. Note that we need to prefix this with a % symbol, to ensure the directory change will persist to the next cells.

In [8]:
%cd cmps3160/_labs

/content/cmps3160/_labs

In [9]:
!pwd

/content/cmps3160/_labs

In [10]:
# Now, we can list the contents of the `_labs` folder.
!ls

data	Lab01  Lab03  Lab05  Lab07  Lab09  Lab11  old	     _tmp.md
images	Lab02  Lab04  Lab06  Lab08  Lab10  Lab12  README.md

In [11]:
# change back the working directory to /content
%cd /content
!ls

/content
cmps3160  sample_data

## Non-persistence of Colab Virtual Machines

An important thing to note about Colab is that files you create during the session will not persist once the runtime shuts down. Google creates these temporary virtual environments to host your notebook, but it shuts them down so the resource can be reallocated to other notebooks. The runtime will shutdown automatically if not used for a few hours, so be careful about files that are created during the session.

This means that the `cmps3160` folder that we just created will disappear if we restart the session. You can test this by clicking on `Runtime->Disconnect and delete Runtime`. If you do so, you'll notice `cmps3160` is gone:

In [12]:
!ls

cmps3160  sample_data

To get it back, you'll have to issue the `git clone` command above again.


While these newly created files will disappear, note that the code you write in this notebook should be fine. It should be saved in the `Colab Notebooks` folder in the root of your Google Drive. Please be sure to save frequently as you are working on assignments.

## Mounting Your Google Drive

On some occasions, you may want to create data that will persist. For example, when working on your course project, you don't want to re-collect any data you need for your analysis.

One way to make this data persist is to write directly to your Google Drive, rather than to this virual machine. To do so, we can use a Python command to "mount" the Google Drive. This will pop up a screen asking you to give this Colab notebook access to your Google Drive. **If you have multiple Google accounts, please be sure to use the same one consistently throughout the course.**:

In [13]:
# Mount our personal google drive. This will pop up a
# confirmation screen giving this notebook access to your Google drive.
# You will first need a gmail account for this to work.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

You should now see the contents of your Google drive by navigating to the folder icon in the left panel. It is viewable at `/content/drive/MyDrive`.

You can also use the `ls` command to list the contents of your Google Drive:

In [14]:
!ls /content/drive/MyDrive

'2021 & 2022 years self-reported grades - Tulane University.gdoc'
'2024-10-22 Cartas Recomendación Randall Herrera.pdf'
'2024 Cartas de Recomendación - Randall H (1).pdf'
'2024 Cartas de Recomendación - Randall H.gdoc'
'2024 Cartas de Recomendación - Randall H.pdf'
'Academic Presentations.gslides'
'ALPFA Application.gdoc'
'Application Withdrawal Template.gdoc'
'Apuntes - Tekkie Uni.gdoc'
'Autobiografía Navarra.gdoc'
'Boom boom.gdoc'
 Brainstorming.gdoc
'calculus II final fall 2025.pdf'
'Carta de Intención para Universidad de Navarra.gdoc'
'Carta de Motivación RH (1).gdoc'
'Carta de Motivación RH.gdoc'
'Clase IA.gdoc'
 Classroom
'CMPS 1500 custom practice exam.gdoc'
'CMPS 1500 Final CheatSheet.gdoc'
'CMPS 1600 UML milestone 2.pdf'
'Colab Notebooks'
'College Fair guide.gdoc'
'College Research.gdoc'
'CollegeVine important info from Sage Chatbot.gdoc'
'CompTIA practice questions.gdoc'
'Computation, Cryogenic Engineering and Aerospace Physics research for Tulane University and NASA Michoud.gdoc'
 coordinacion8@cca.edu.ni.gslides
'Copy of College Fair: Questions to ask.gdoc'
'Copy of Draft 12 of College Essay - Randall Herrera rev. RH.gdoc'
'Copy of Draft 2 (Draft 3) of College Essay.gdoc'
'Copy of Keiser Advanced English Course..gdoc'
'Copy of Keiser Roleplay.gdoc'
'Copy of sda gjkapeiuvbsKLFms.gdoc'
'Copy of "Why us?" Essay Research Chart 2.0 - Template to Copy.gdoc'
'Data Center Internship.gdoc'
'Discrete Math problems.gdoc'
'Draft 12 of College Essay - Randall Herrera rev. RH.gdoc'
'Draft 2 of Texas Christian Univeristy Supplement.gdoc'
'EAPP 1000: Outline.gdoc'
'Ejercicios Navarra.gdoc'
'Essay outline 2.gdoc'
'Evolution of Engineering and ties to the Industrial Revolutions over the years.gdoc'
'Final Project Script v2.gdoc'
 Foro.gdoc
'GDG API.gslides'
"GDG: Randall's Event Idea: Team Prompt + Firebase Challenge with GDG @ TU.gdoc"
'Getting started.pdf'
'Google Keep Document.gdoc'
'Grupo #   "B".gsite'
'Guión Filo.gdoc'
'https:  www.google.com search?q=logo+del+cca&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjFsoy91M7nAhVMnFkKHfQPCjUQ_AUoAXoECAwQAw&biw=1366&bih=657#imgrc=YHbuIPCL6HWXqM.gsite'
 hw.gdoc
'Impromptu speech exercise..gdoc'
'Inspiring statement and random thoughts out of boredom.gdoc'
'INTD 2811 - Final CheckPoint.gdoc'
'INTD 2811 Final Exam Printout.gdoc'
'Internship for resume.gdoc'
'Interview script.gdoc'
'Keiser Advanced English Course..gdoc'
'Keiser Compare and Contrast Essay.gdoc'
'Keiser Dialogue.gdoc'
'Keiser Podcast.gdoc'
'Keiser Roleplay.gdoc'
'Keiser script.gdoc'
'Keiser Story.gdoc'
'Luis’ reported speech.gdoc'
'March 28’s activity:.gdoc'
'Me mandaron a casa.gdoc'
'Multicultural Speech Presentation.gslides'
'Multicultural Speech Presentation Script.gdoc'
'Multicultural Speech Questions.gdoc'
 NOTES.gdoc
'Oración por la patria.gdoc'
'Perception EAPP 1000 Activity.gdoc'
'Persuasive Essay.gdoc'
'Persuasive Speech.gdoc'
'Presentations Activity Report.gdoc'
'Python from Excercism.gdoc'
'Qualities list.gdoc'
 Questions.gdoc
'Randall Herrera - College Planner.gsheet'
 Randall_Herrera_Resume.pdf
'Randall Herrera Submission-Checkpoint2.docx'
"Randall's SAT practice tests answers.gdoc"
'Reach out email draft for Professor Matt Barrios.gdoc'
'Required Questions.gdoc'
'Response for professor.gdoc'
'Role Play script.gdoc'
'SAT Progress Report (Randall Herrera) (1).gdoc'
'SAT Progress Report (Randall Herrera).gdoc'
'SAT Progress Report (Randall Herrera).pdf'
'Software Development Life Cycle notes.gdoc'
'Solicitud de Admisión 2025-26.docx'
'Speaking Activity.gdoc'
'Story activity.gdoc'
'Storytelling assignment.gdoc'
'Storytelling: Expressing emotions.gdoc'
'Supplemental clinic.gdoc'
'Supps ideas for TCU.gdoc'
 Tareas.gdoc
 test_file.txt
'Texas Christian Univeristy Supplement jbedit.gdoc'
'Things to do & learn before college.gdoc'
 Timeline.gdoc
'TOEFL PRACTICE.gdoc'
'Tulane Computer Science and Engineering Physics.gdoc'
'Tulane Engineering Physics research.gdoc'
'[TULANE GDGC] Midterm 1 Practice - CMPS 1500 - Fall '\''25 copy.gdoc'
 Tulane.gdoc
 Tulane.pdf
'UDEMY: IT Fundamentals - Everything you need to know about IT.gdoc'
 Universidades.gdoc
'Untitled document (1).gdoc'
'Untitled document.gdoc'
'Untitled presentation.gslides'
'US VISA QUESTIONS.gdoc'
'Warranty Deed.pdf'

To change the current working directory to be the location of your Google drive, we will issue a `cd` command preceded by the % symbol. The difference between ! and % is that % will actually have a persistent effect on the notebook.

In [15]:
%cd /content/drive/My Drive

/content/drive/My Drive

In [16]:
!pwd

/content/drive/My Drive

To test that this works, we will create a text file and write a sentence to it.

In [17]:
outf = open('test_file.txt', 'wt')
outf.write('Hello from Colab!')
outf.close()

We can see that this file exists by printing its contents here:

In [18]:
!cat test_file.txt

Hello from Colab!

You should also see this file when you navigate to your Google Drive separately in your browser.

This file will remain here even if you shutdown the runtime of this notebook.

## Data for Labs

The data used in the labs is in the `_labs/data` folder of the course repository.

Since we already cloned the repository, let's naviage to the `_labs` folder:

In [19]:
%cd /content/cmps3160/_labs/
!ls

/content/cmps3160/_labs
data	Lab01  Lab03  Lab05  Lab07  Lab09  Lab11  old	     _tmp.md
images	Lab02  Lab04  Lab06  Lab08  Lab10  Lab12  README.md

The `data` folder contains all the data used for the labs.

In [20]:
!ls data

ames.tsv  movielens.zip  names.zip  reds.csv  tips.csv	titanic.csv  whites.csv

The next lab will work with the file `titanic.csv`, which contains information on passengers of the ill-fated Titanic passenger ship. You can use the command `head` to see the first ten lines of this file.

In [21]:
!head data/titanic.csv

﻿pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,,"St Louis, MO"
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,,"Montreal, PQ / Chesterville, ON"
1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.5500,C22 C26,S,,,"Montreal, PQ / Chesterville, ON"
1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.5500,C22 C26,S,,135,"Montreal, PQ / Chesterville, ON"
1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.5500,C22 C26,S,,,"Montreal, PQ / Chesterville, ON"
1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.5500,E12,S,3,,"New York, NY"
1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,,"Hudson, NY"
1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0.0000,A36,S,,,"Belfast, NI"
1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,,"Bayside, Queens, NY"

We can see that this is a comma-separated file, where each row contains information on a ship passenger.

## Pandas

Pandas is a Python library that we will be using extensively to store and analyze data. You can find a brief overview of Pandas [here](https://pandas.pydata.org/docs/user_guide/10min.html).

The key data structure in Pandas is the [DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html), which is conceptually similar to an Excel spreadsheet.

Below, we import the `pandas` library and read `titanic.csv` into a new DataFrame object called `df`.

Note that the path we enter here will depend on the current working directory. Here, we assume we are already in the `/content/cmps3160/_labs` folder, so we use the **relative path** `data/titanic.csv` in order to read in the file. This path is relative to the current working directory.

We can print the first five rows of the DataFrame using the `.head()` command.

In [22]:
import pandas as pd
df = pd.read_csv('data/titanic.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [23]:
# How many rows are there?
len(df)

1309

In the next labs, will work with DataFrames in more detail. For now, please complete the short exercises below and submit your notebook to Canvas,

## Exercises

### Exercise 1
Change the current working directory to the folder in `cmps3160/_demos/data/`.

In [24]:
# TODO: your code here
%cd /content/cmps3160/_demos/data/

/content/cmps3160/_demos/data

Expected output:

```
/content/cmps3160/_demos/data
```

### Exercise 2
List the contents of this directory.

In [25]:
# TODO: your code here
!ls

adult.csv      boundry.png  nba_salaries.csv  review_polarity.zip
billboard.csv  iris.csv     nba_stats.csv     titanic.csv
bodyfat.csv    iris.png     religon.csv

Expected output:

```
adult.csv      boundry.png  nba_salaries.csv  review_polarity.zip
billboard.csv  iris.csv     nba_stats.csv     titanic.csv
bodyfat.csv    iris.png     religon.csv
```

### Exercise 3
 Oh look, there's another `titanic.csv` file in here. Read it into a new DataFrame called `df2` and print the first row.

In [26]:
# TODO: your code here
df2 = pd.read_csv("titanic.csv")
df2.head(1)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"

### Exercise 4
DataFrame objects have a  `.describe()` method that summarizes the data. Run it below:

In [27]:
# TODO: your code here
df2.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

Expected output:


|       |      pclass |    survived |       age |       sibsp |       parch |      fare |     body |
|:------|------------:|------------:|----------:|------------:|------------:|----------:|---------:|
| count | 1309        | 1309        | 1046      | 1309        | 1309        | 1308      | 121      |
| mean  |    2.29488  |    0.381971 |   29.8811 |    0.498854 |    0.385027 |   33.2955 | 160.81   |
| std   |    0.837836 |    0.486055 |   14.4135 |    1.04166  |    0.86556  |   51.7587 |  97.6969 |
| min   |    1        |    0        |    0.1667 |    0        |    0        |    0      |   1      |
| 25%   |    2        |    0        |   21      |    0        |    0        |    7.8958 |  72      |
| 50%   |    3        |    0        |   28      |    0        |    0        |   14.4542 | 155      |
| 75%   |    3        |    1        |   39      |    1        |    0        |   31.275  | 256      |
| max   |    3        |    1        |   80      |    8        |    9        |  512.329  | 328      |

### Exercise 5

Using only the output of the previous cell and the [method documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) answer the following questions.

Hint: you shouldn't write any code, think about the range of possible values for a column when interpreting the summary stats.

**5a. What fraction of passengers survived (rounded to two decimal places)?**

Fraction of people who survived: 0.381971 ~ 0.38. Roughly 38% (38/100).

**5b. What was the median fare (rounded to the nearest dollar)?**

Median fare: 14.4542 ~ $**14**

**5c. Were there more 1st class passengers or 3rd class passengers?**

There were more people in the 3rd class, because both the median (50%) and the 75th percentile are class 3.

**To submit:**

1. File->Download .ipynb
2. Upload the .ipynb file to the appropriate assignment in [Canvas](https://tulane.instructure.com/)